import { useQuery } from "react-query"
import axios from "axios"

const mockData = [
    {
        token_id: 1,
        token_uri: "https://champions.io/champions/nfts/1",
        current_owner: "0x20c5954A11B9fc625Cc91e976E2933c0471f3bF2",
        name: "Champion #1",
        Ascension: "Eternal",
        Claws: "C \ud83c\udf31  Imbued",
        "Core Essence": "\ud83d\udc80 Death",
        "Divine Parts": 2,
        Divinity: "2",
        Edition: "Prime",
        Family: "Il\u2019gra",
        Fangs: "D \ud83d\udc80 Rotbite",
        Hairstyle: "E - Dual Basil",
        Halo: "Formidable",
        Horns: "D \ud83d\udd2e Bloodskewer",
        Piercing: "C - Classic",
        Purity: "2",
        Tail: "R \ud83c\udf31  Prideback",
        Warpaint: "C \ud83d\udc80 Loneliness",
        Wings: "None",
    },
    {
        token_id: 2,
        token_uri: "https://champions.io/champions/nfts/2",
        current_owner: "0x5B0cDF5369295B6EF918BBAb8b38a11d574AafFb",
        name: "Champion #2",
        Ascension: "Eternal",
        Claws: "C \ud83d\udc80 Elongated ",
        "Core Essence": "\ud83c\udf31  Life",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Il\u2019gra",
        Fangs: "C \ud83d\udc80 Solitary",
        Hairstyle: "R - Dual Green",
        Halo: "Auspicious",
        Horns: "C \ud83c\udf31  Bharal",
        Piercing: "C - Classic",
        Purity: "2",
        Tail: "C \ud83c\udf31  Feathershine",
        Warpaint: "R \ud83d\udd2e Discipline",
        Wings: "None",
    },
    {
        token_id: 3,
        token_uri: "https://champions.io/champions/nfts/3",
        current_owner: "0x51EF6A683256a5B8bdbF197ba50bfedf02f7245a",
        name: "Champion #3",
        Ascension: "Eternal",
        Claws: "None",
        "Core Essence": "\ud83d\udd2e Arcane",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Darulk",
        Fangs: "R \ud83c\udf31  Decorous",
        Hairstyle: "C - Scarlet Long",
        Halo: "Majestic",
        Horns: "R \ud83c\udf31  Moose",
        Piercing: "C - Classic",
        Purity: "1",
        Tail: "R \ud83d\udd2e Tigris",
        Warpaint: "R \ud83d\udc80 Conflict",
        Wings: "R \ud83d\udc80 Nightbug",
    },
    {
        token_id: 4,
        token_uri: "https://champions.io/champions/nfts/4",
        current_owner: "0xe63CdCDb22D01ec60cA833452D6c09CA49938dE5",
        name: "Champion #4",
        Ascension: "Eternal",
        Claws: "R \ud83c\udf31  Cartilage",
        "Core Essence": "\ud83c\udf31  Life",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Keymaster",
        Fangs: "C \ud83d\udc80 Solitary",
        Hairstyle: "C - Dark Rising",
        Halo: "Auspicious",
        Horns: "R \ud83d\udd2e Oni",
        Piercing: "E - Rings",
        Purity: "1",
        Tail: "None",
        Warpaint: "R \ud83d\udc80 Lamentation",
        Wings: "C \ud83d\udd2e Soarplume",
    },
    {
        token_id: 5,
        token_uri: "https://champions.io/champions/nfts/5",
        current_owner: "0xc9e6b57dE8fe0fdb83B3ac36166E8DD6a2C4bECA",
        name: "Champion #5",
        Ascension: "Eternal",
        Claws: "C \ud83d\udd2e Spinegrowth",
        "Core Essence": "\ud83c\udf31  Life",
        "Divine Parts": 1,
        Divinity: "1",
        Edition: "Prime",
        Family: "Grondal",
        Fangs: "D \ud83d\udc80 Rotbite",
        Hairstyle: "C - No Hair",
        Halo: "Providential",
        Horns: "C \ud83d\udc80 Charger",
        Piercing: "C - Classic",
        Purity: "0",
        Tail: "C \ud83d\udd2e Shiftplume",
        Warpaint: "C \ud83d\udd2e Adage",
        Wings: "None",
    },
    {
        token_id: 6,
        token_uri: "https://champions.io/champions/nfts/6",
        current_owner: "0xB3846e8A6A230A5A853867f24Ecd7AE800CAe967",
        name: "Champion #6",
        Ascension: "Eternal",
        Claws: "C \ud83c\udf31  Imbued",
        "Core Essence": "\ud83d\udc80 Death",
        "Divine Parts": 1,
        Divinity: "1",
        Edition: "Prime",
        Family: "Aos",
        Fangs: "D \ud83d\udc80 Rotbite",
        Hairstyle: "R - Gravely Black",
        Halo: "Daunting",
        Horns: "None",
        Piercing: "C - Classic",
        Purity: "1",
        Tail: "C \ud83c\udf31  Griffin",
        Warpaint: "R \ud83c\udf31  Family",
        Wings: "C \ud83c\udf31  Sagebird",
    },
    {
        token_id: 7,
        token_uri: "https://champions.io/champions/nfts/7",
        current_owner: "0x02a0780f4148BD88eae770385a2691e22346c9C2",
        name: "Champion #7",
        Ascension: "Eternal",
        Claws: "C \ud83c\udf31  Construct",
        "Core Essence": "\ud83c\udf31  Life",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Fenrir",
        Fangs: "C \ud83d\udd2e Incisors",
        Hairstyle: "E - Pink Wolfstripe",
        Halo: "Hopeful",
        Horns: "E \ud83c\udf31  Mar",
        Piercing: "R - Bone",
        Purity: "3",
        Tail: "C \ud83c\udf31  Bliss",
        Warpaint: "None",
        Wings: "C \ud83d\udd2e Levitation",
    },
    {
        token_id: 8,
        token_uri: "https://champions.io/champions/nfts/8",
        current_owner: "0xF52b21144F13DFC4d4E7Ffbd912C13b9dA1e6f8E",
        name: "Champion #8",
        Ascension: "Eternal",
        Claws: "None",
        "Core Essence": "\ud83d\udd2e Arcane",
        "Divine Parts": 1,
        Divinity: "1",
        Edition: "Prime",
        Family: "Whisperer",
        Fangs: "C \ud83d\udc80 Hungering",
        Hairstyle: "E - White Slick-back",
        Halo: "Grandiose",
        Horns: "D \ud83d\udc80 Malevolence",
        Piercing: "C - Stud",
        Purity: "1",
        Tail: "C \ud83d\udd2e Shiftplume",
        Warpaint: "C \ud83c\udf31  Reality",
        Wings: "C \ud83c\udf31  Sagebird",
    },
    {
        token_id: 9,
        token_uri: "https://champions.io/champions/nfts/9",
        current_owner: "0x3380875760555912EC3E985ceB8b9b4b2A9157D6",
        name: "Champion #9",
        Ascension: "Eternal",
        Claws: "C \ud83d\udd2e Conjurer",
        "Core Essence": "\ud83c\udf31  Life",
        "Divine Parts": 1,
        Divinity: "1",
        Edition: "Prime",
        Family: "Gatekeeper",
        Fangs: "D \ud83c\udf31  Soulpiercer",
        Hairstyle: "C - Plucked Amber",
        Halo: "Propitious",
        Horns: "C \ud83d\udc80 Striker",
        Piercing: "C - Stud",
        Purity: "2",
        Tail: "None",
        Warpaint: "R \ud83c\udf31  Ancestry",
        Wings: "C \ud83d\udc80 Swampstrider",
    },
    {
        token_id: 10,
        token_uri: "https://champions.io/champions/nfts/10",
        current_owner: "0xB0603BDb6D0d94eA126E8A6dbaC41Cf783E60beE",
        name: "Champion #10",
        Ascension: "Eternal",
        Claws: "C \ud83d\udc80 Feral",
        "Core Essence": "\ud83d\udd2e Arcane",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Vitra",
        Fangs: "None",
        Hairstyle: "C - Classic Ponytail",
        Halo: "Grandiose",
        Horns: "C \ud83c\udf31  Bharal",
        Piercing: "C - Classic",
        Purity: "1",
        Tail: "E \ud83c\udf31  Peacock",
        Warpaint: "C \ud83c\udf31  Birth",
        Wings: "C \ud83d\udd2e Bluechirp",
    },
    {
        token_id: 11,
        token_uri: "https://champions.io/champions/nfts/11",
        current_owner: "0x01C0cDd9F051EcF9ae9Cf541c317deCa7A473193",
        name: "Champion #11",
        Ascension: "Eternal",
        Claws: "R \ud83c\udf31  Peregrine",
        "Core Essence": "\ud83d\udd2e Arcane",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Il\u2019gra",
        Fangs: "R \ud83d\udc80 Sidetooth",
        Hairstyle: "R - Dual Green",
        Halo: "Magnificent",
        Horns: "C \ud83c\udf31  Takin",
        Piercing: "C - Classic",
        Purity: "2",
        Tail: "C \ud83d\udd2e Plategrom",
        Warpaint: "C \ud83d\udd2e Lore",
        Wings: "None",
    },
    {
        token_id: 12,
        token_uri: "https://champions.io/champions/nfts/12",
        current_owner: "0xEc206aAd6416478443F6a47b0C900AF8A7A98675",
        name: "Champion #12",
        Ascension: "Eternal",
        Claws: "None",
        "Core Essence": "\ud83d\udc80 Death",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Darulk",
        Fangs: "R \ud83d\udc80 Gnasher",
        Hairstyle: "R - Purple Long",
        Halo: "Formidable",
        Horns: "C \ud83c\udf31  Takin",
        Piercing: "C - Stud",
        Purity: "2",
        Tail: "C \ud83d\udc80 Leandrake",
        Warpaint: "C \ud83d\udd2e Adage",
        Wings: "C \ud83d\udd2e Bluechirp",
    },
    {
        token_id: 13,
        token_uri: "https://champions.io/champions/nfts/13",
        current_owner: "0xaFA158D67798c70E4acF241599250E8f2cC6740C",
        name: "Champion #13",
        Ascension: "Eternal",
        Claws: "R \ud83d\udd2e Hooked",
        "Core Essence": "\ud83d\udc80 Death",
        "Divine Parts": 1,
        Divinity: "1",
        Edition: "Prime",
        Family: "Il\u2019gra",
        Fangs: "D \ud83d\udd2e Riddlegash",
        Hairstyle: "E - Dual Basil",
        Halo: "Imposing",
        Horns: "R \ud83d\udc80 Regal",
        Piercing: "C - Classic",
        Purity: "2",
        Tail: "E \ud83d\udc80 Noxious",
        Warpaint: "C \ud83d\udd2e History",
        Wings: "None",
    },
    {
        token_id: 14,
        token_uri: "https://champions.io/champions/nfts/14",
        current_owner: "0xdd7D6305b430b9B7D72a94D77B64FB76335c30E8",
        name: "Champion #14",
        Ascension: "Eternal",
        Claws: "R \ud83c\udf31  Cartilage",
        "Core Essence": "\ud83d\udd2e Arcane",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Aos",
        Fangs: "R \ud83d\udc80 Gnasher",
        Hairstyle: "C - Gravely Blonde",
        Halo: "Splendid",
        Horns: "None",
        Piercing: "C - Classic",
        Purity: "1",
        Tail: "C \ud83d\udc80 Wurm",
        Warpaint: "R \ud83d\udd2e Discipline",
        Wings: "C \ud83d\udc80 Raventalon",
    },
    {
        token_id: 15,
        token_uri: "https://champions.io/champions/nfts/15",
        current_owner: "0x89C5f1EF5084908004bceF44d5E5680abCb49FB3",
        name: "Champion #15",
        Ascension: "Eternal",
        Claws: "None",
        "Core Essence": "\ud83d\udd2e Arcane",
        "Divine Parts": 1,
        Divinity: "1",
        Edition: "Prime",
        Family: "Darulk",
        Fangs: "C \ud83d\udc80 Hungering",
        Hairstyle: "C - Scarlet Long",
        Halo: "Splendid",
        Horns: "D \ud83d\udd2e Bloodskewer",
        Piercing: "C - Classic",
        Purity: "3",
        Tail: "R \ud83d\udd2e Tigris",
        Warpaint: "C \ud83d\udd2e History",
        Wings: "C \ud83c\udf31  Sagebird",
    },
    {
        token_id: 16,
        token_uri: "https://champions.io/champions/nfts/16",
        current_owner: "0xD4818d4C5d0c689e9569C73321910C4774Ad4d52",
        name: "Champion #16",
        Ascension: "Eternal",
        Claws: "D \ud83d\udd2e Gutripper",
        "Core Essence": "\ud83c\udf31  Life",
        "Divine Parts": 1,
        Divinity: "1",
        Edition: "Prime",
        Family: "Keymaster",
        Fangs: "C \ud83c\udf31  Sangreal",
        Hairstyle: "C - Blue Rising",
        Halo: "Propitious",
        Horns: "C \ud83c\udf31  Bharal",
        Piercing: "R - Bone",
        Purity: "3",
        Tail: "None",
        Warpaint: "C \ud83c\udf31  Reality",
        Wings: "R \ud83d\udc80 Nightbug",
    },
    {
        token_id: 17,
        token_uri: "https://champions.io/champions/nfts/17",
        current_owner: "0xB733B82341B2f0cD788beF1482c8cA4b6896F354",
        name: "Champion #17",
        Ascension: "Eternal",
        Claws: "None",
        "Core Essence": "\ud83d\udd2e Arcane",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Darulk",
        Fangs: "C \ud83c\udf31  Sangreal",
        Hairstyle: "C - Scarlet Long",
        Halo: "Majestic",
        Horns: "C \ud83d\udc80 Striker",
        Piercing: "R - Bone",
        Purity: "0",
        Tail: "C \ud83c\udf31  Griffin",
        Warpaint: "R \ud83d\udc80 Lamentation",
        Wings: "R \ud83c\udf31  Odonata",
    },
    {
        token_id: 18,
        token_uri: "https://champions.io/champions/nfts/18",
        current_owner: "0x4C831B771CCCfF7B4b1356E11161f4726383d3F3",
        name: "Champion #18",
        Ascension: "Eternal",
        Claws: "C \ud83c\udf31  Appendix",
        "Core Essence": "\ud83d\udd2e Arcane",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Seris",
        Fangs: "None",
        Hairstyle: "R - Mountain Brown",
        Halo: "Splendid",
        Horns: "R \ud83d\udd2e Oni",
        Piercing: "C - Classic",
        Purity: "2",
        Tail: "C \ud83d\udc80 Moonfang",
        Warpaint: "C \ud83d\udd2e History",
        Wings: "R \ud83c\udf31  Odonata",
    },
    {
        token_id: 19,
        token_uri: "https://champions.io/champions/nfts/19",
        current_owner: "0xaFA158D67798c70E4acF241599250E8f2cC6740C",
        name: "Champion #19",
        Ascension: "Eternal",
        Claws: "C \ud83c\udf31  Imbued",
        "Core Essence": "\ud83d\udc80 Death",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Vitra",
        Fangs: "None",
        Hairstyle: "R - Brown Ponytail",
        Halo: "Formidable",
        Horns: "C \ud83d\udd2e Antler",
        Piercing: "C - Classic",
        Purity: "1",
        Tail: "C \ud83c\udf31  Griffin",
        Warpaint: "C \ud83d\udc80 Loneliness",
        Wings: "C \ud83c\udf31  Sagebird",
    },
    {
        token_id: 20,
        token_uri: "https://champions.io/champions/nfts/20",
        current_owner: "0xaFA158D67798c70E4acF241599250E8f2cC6740C",
        name: "Champion #20",
        Ascension: "Eternal",
        Claws: "C \ud83d\udc80 Sharpened",
        "Core Essence": "\ud83d\udd2e Arcane",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Fenrir",
        Fangs: "C \ud83c\udf31  Fleshpiercer",
        Hairstyle: "C - White Wolfstripe",
        Halo: "Magnificent",
        Horns: "R \ud83d\udc80 Anoa",
        Piercing: "C - Stud",
        Purity: "1",
        Tail: "C \ud83d\udd2e Plategrom",
        Warpaint: "None",
        Wings: "E \ud83d\udc80 Boneframe",
    },
    {
        token_id: 21,
        token_uri: "https://champions.io/champions/nfts/21",
        current_owner: "0x9eA6d85ad6aeb8A3bB34140dF9c027B6b264069D",
        name: "Champion #21",
        Ascension: "Eternal",
        Claws: "D \ud83c\udf31  Heartseeker",
        "Core Essence": "\ud83c\udf31  Life",
        "Divine Parts": 1,
        Divinity: "1",
        Edition: "Prime",
        Family: "Aos",
        Fangs: "C \ud83c\udf31  Sangreal",
        Hairstyle: "C - Gravely White",
        Halo: "Hopeful",
        Horns: "None",
        Piercing: "C - Classic",
        Purity: "3",
        Tail: "C \ud83d\udc80 Moonfang",
        Warpaint: "C \ud83d\udc80 Midnight",
        Wings: "R \ud83c\udf31  Odonata",
    },
    {
        token_id: 22,
        token_uri: "https://champions.io/champions/nfts/22",
        current_owner: "0xcB7d7ABd39f647707182E32a5b9e3EA42A565bF5",
        name: "Champion #22",
        Ascension: "Eternal",
        Claws: "D \ud83d\udc80 Marrowstrike",
        "Core Essence": "\ud83d\udd2e Arcane",
        "Divine Parts": 1,
        Divinity: "1",
        Edition: "Prime",
        Family: "Saadari",
        Fangs: "C \ud83d\udd2e Craving",
        Hairstyle: "C - Scarlethooks",
        Halo: "Grandiose",
        Horns: "None",
        Piercing: "E - Rings",
        Purity: "2",
        Tail: "C \ud83d\udd2e Shiftplume",
        Warpaint: "C \ud83c\udf31  Inertia",
        Wings: "C \ud83d\udc80 Carcass",
    },
    {
        token_id: 23,
        token_uri: "https://champions.io/champions/nfts/23",
        current_owner: "0xd722B0584286Fdb7a99A4Becb55B57971d62BbD8",
        name: "Champion #23",
        Ascension: "Eternal",
        Claws: "R \ud83d\udc80 Overarching",
        "Core Essence": "\ud83c\udf31  Life",
        "Divine Parts": 2,
        Divinity: "2",
        Edition: "Prime",
        Family: "Fenrir",
        Fangs: "C \ud83d\udd2e Craving",
        Hairstyle: "R - Brown Wolfstripe",
        Halo: "Auspicious",
        Horns: "D \ud83c\udf31  Endgame",
        Piercing: "C - Classic",
        Purity: "1",
        Tail: "D \ud83d\udc80 Doomscale",
        Warpaint: "None",
        Wings: "C \ud83d\udd2e Levitation",
    },
    {
        token_id: 24,
        token_uri: "https://champions.io/champions/nfts/24",
        current_owner: "0x02f1ECAd208fcaB5A81Efdd93ecAF2f6C670Af16",
        name: "Champion #24",
        Ascension: "Eternal",
        Claws: "D \ud83d\udd2e Gutripper",
        "Core Essence": "\ud83d\udd2e Arcane",
        "Divine Parts": 1,
        Divinity: "1",
        Edition: "Prime",
        Family: "Keymaster",
        Fangs: "C \ud83d\udd2e Saber",
        Hairstyle: "C - Blue Rising",
        Halo: "Magnificent",
        Horns: "R \ud83d\udc80 Anoa",
        Piercing: "C - Classic",
        Purity: "2",
        Tail: "None",
        Warpaint: "C \ud83c\udf31  Birth",
        Wings: "R \ud83c\udf31  Odonata",
    },
    {
        token_id: 25,
        token_uri: "https://champions.io/champions/nfts/25",
        current_owner: "0xEDBa61C18c7cc93c6D5AEee44472Be318420B471",
        name: "Champion #25",
        Ascension: "Eternal",
        Claws: "C \ud83d\udc80 Feral",
        "Core Essence": "\ud83d\udc80 Death",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Karkadon",
        Fangs: "R \ud83c\udf31  Razor",
        Hairstyle: "C - No Hair",
        Halo: "Imposing",
        Horns: "C \ud83d\udd2e Eland",
        Piercing: "C - Classic",
        Purity: "2",
        Tail: "R \ud83d\udd2e Tigris",
        Warpaint: "None",
        Wings: "R \ud83d\udc80 Tentacled",
    },
    {
        token_id: 26,
        token_uri: "https://champions.io/champions/nfts/26",
        current_owner: "0xcfe1CCF15327a6Bd64Cf52C9387fF0Ba16D69C41",
        name: "Champion #26",
        Ascension: "Eternal",
        Claws: "D \ud83c\udf31  Heartseeker",
        "Core Essence": "\ud83c\udf31  Life",
        "Divine Parts": 2,
        Divinity: "2",
        Edition: "Prime",
        Family: "Seris",
        Fangs: "None",
        Hairstyle: "R - Mountain Brown",
        Halo: "Auspicious",
        Horns: "R \ud83c\udf31  Moose",
        Piercing: "C - Classic",
        Purity: "5",
        Tail: "D \ud83c\udf31  Dawnsong",
        Warpaint: "C \ud83c\udf31  Reality",
        Wings: "R \ud83c\udf31  Mothlight",
    },
    {
        token_id: 27,
        token_uri: "https://champions.io/champions/nfts/27",
        current_owner: "0xaFA158D67798c70E4acF241599250E8f2cC6740C",
        name: "Champion #27",
        Ascension: "Eternal",
        Claws: "C \ud83d\udd2e Spinegrowth",
        "Core Essence": "\ud83d\udd2e Arcane",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Saadari",
        Fangs: "R \ud83c\udf31  Razor",
        Hairstyle: "R - Greenhooks",
        Halo: "Splendid",
        Horns: "None",
        Piercing: "R - Bone",
        Purity: "2",
        Tail: "R \ud83d\udc80 Bonestinger",
        Warpaint: "R \ud83d\udc80 Lamentation",
        Wings: "C \ud83d\udd2e Levitation",
    },
    {
        token_id: 28,
        token_uri: "https://champions.io/champions/nfts/28",
        current_owner: "0x1eFFF6682F30e9Fa7C5fd7ec6138d006eafD137B",
        name: "Champion #28",
        Ascension: "Eternal",
        Claws: "C \ud83d\udc80 Sharpened",
        "Core Essence": "\ud83d\udd2e Arcane",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Aos",
        Fangs: "C \ud83d\udd2e Craving",
        Hairstyle: "C - Gravely Blonde",
        Halo: "Magnificent",
        Horns: "None",
        Piercing: "C - Stud",
        Purity: "1",
        Tail: "C \ud83d\udc80 Wurm",
        Warpaint: "R \ud83d\udc80 Conflict",
        Wings: "E \ud83d\udc80 Boneframe",
    },
    {
        token_id: 29,
        token_uri: "https://champions.io/champions/nfts/29",
        current_owner: "0xC95E687C5F1850C114ba4439b568fAB7dB9D902C",
        name: "Champion #29",
        Ascension: "Eternal",
        Claws: "C \ud83c\udf31  Appendix",
        "Core Essence": "\ud83c\udf31  Life",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Karkadon",
        Fangs: "R \ud83c\udf31  Razor",
        Hairstyle: "C - Sage Ponytail",
        Halo: "Hopeful",
        Horns: "C \ud83d\udd2e Eland",
        Piercing: "C - Classic",
        Purity: "3",
        Tail: "C \ud83c\udf31  Feathershine",
        Warpaint: "None",
        Wings: "R \ud83d\udc80 Tentacled",
    },
    {
        token_id: 30,
        token_uri: "https://champions.io/champions/nfts/30",
        current_owner: "0xF5F5238dB66194835F90DF511cC7C8Ff02E0660a",
        name: "Champion #30",
        Ascension: "Eternal",
        Claws: "D \ud83c\udf31  Heartseeker",
        "Core Essence": "\ud83d\udc80 Death",
        "Divine Parts": 1,
        Divinity: "1",
        Edition: "Prime",
        Family: "Gatekeeper",
        Fangs: "C \ud83d\udc80 Solitary",
        Hairstyle: "C - Plucked Amber",
        Halo: "Daunting",
        Horns: "C \ud83d\udc80 Striker",
        Piercing: "C - Classic",
        Purity: "3",
        Tail: "None",
        Warpaint: "C \ud83d\udd2e Adage",
        Wings: "C \ud83d\udc80 Carcass",
    },
    {
        token_id: 31,
        token_uri: "https://champions.io/champions/nfts/31",
        current_owner: "0xc703b0cdD619258BE670d796f19B45A844CFe2C7",
        name: "Champion #31",
        Ascension: "Eternal",
        Claws: "None",
        "Core Essence": "\ud83c\udf31  Life",
        "Divine Parts": 2,
        Divinity: "2",
        Edition: "Prime",
        Family: "Whisperer",
        Fangs: "D \ud83d\udd2e Riddlegash",
        Hairstyle: "C - Black Slick-back",
        Halo: "Auspicious",
        Horns: "C \ud83d\udd2e Eland",
        Piercing: "C - Stud",
        Purity: "2",
        Tail: "D \ud83d\udd2e Gravelash",
        Warpaint: "C \ud83c\udf31  Inertia",
        Wings: "C \ud83c\udf31  Sagebird",
    },
    {
        token_id: 32,
        token_uri: "https://champions.io/champions/nfts/32",
        current_owner: "0xb0F47c1dAD4824c0ADe3570e6c4F69899d58500D",
        name: "Champion #32",
        Ascension: "Eternal",
        Claws: "C \ud83d\udd2e Spinegrowth",
        "Core Essence": "\ud83d\udc80 Death",
        "Divine Parts": 0,
        Divinity: "0",
        Edition: "Prime",
        Family: "Vitra",
        Fangs: "None",
        Hairstyle: "E - Silver Ponytail",
        Halo: "Forbidding",
        Horns: "R \ud83d\udc80 Anoa",
        Piercing: "C - Classic",
        Purity: "2",
        Tail: "C \ud83d\udd2e Scalecoat",
        Warpaint: "R \ud83d\udc80 Lamentation",
        Wings: "C \ud83c\udf31  Sunsparked",
    },
    {
        token_id: 33,
        token_uri: "https://champions.io/champions/nfts/33",
        current_owner: "0x73183A1B0B8CACDC76157E375acC37d56eB91e2d",
        name: "Champion #33",
        Ascension: "Eternal",
        Claws: "D \ud83d\udc80 Marrowstrike",
        "Core Essence": "\ud83d\udc80 Death",
        "Divine Parts": 3,
        Divinity: "3",
        Edition: "Prime",
        Family: "Aos",
        Fangs: "D \ud83d\udc80 Rotbite",
        Hairstyle: "R - Gravely Black",
        Halo: "Imposing",
        Horns: "None",
        Piercing: "C - Classic",
        Purity: "3",
        Tail: "D \ud83c\udf31  Dawnsong",
        Warpaint: "C \ud83d\udc80 Loneliness",
        Wings: "R \ud83c\udf31  Odonata",
    },
    {
        token_id: 34,
        token_uri: "https://champions.io/champions/nfts/34",
        current_owner: "0x4155f09A168c95EF880B88093982769a6C2cf67d",
        name: "Champion #34",
        Ascension: "Eternal",
        Claws: "C \ud83d\udc80 Feral",
        "Core Essence": "\ud83d\udc80 Death",
        "Divine Parts": 1,
        Divinity: "1",
        Edition: "Prime",
        Family: "Aos",
        Fangs: "R \ud83c\udf31  Decorous",
        Hairstyle: "C - Gravely Blonde",
        Halo: "Formidable",
        Horns: "None",
        Piercing: "C - Stud",
        Purity: "1",
        Tail: "D \ud83c\udf31  Dawnsong",
        Warpaint: "C \ud83c\udf31  Reality",
        Wings: "R \ud83d\udd2e Flightframe",
    },
    {
        token_id: 35,
        token_uri: "https://champions.io/champions/nfts/35",
        current_owner: "0xba6cAA5734c4E1Bba0B40A960ADf0208B7e816BD",
        name: "Champion #35",
        Ascension: "Eternal",
        Claws: "C \ud83c\udf31  Imbued",
        "Core Essence": "\ud83d\udc80 Death",
        "Divine Parts": 1,
        Divinity: "1",
        Edition: "Prime",
        Family: "Keymaster",
        Fangs: "R \ud83c\udf31  Decorous",
        Hairstyle: "C - Dark Rising",
        Halo: "Formidable",
        Horns: "D \ud83d\udd2e Bloodskewer",
        Piercing: "E - Rings",
        Purity: "1",
        Tail: "None",
        Warpaint: "C \ud83d\udc80 Midnight",
        Wings: "R \ud83d\udd2e Soarfin",
    },
]

const fetchTokenData = () => {
    // return axios.get(
    //     "https://s3.amazonaws.com/data.moonstream.to/dev/armory/champions_ascension/pec/data.json"
    // )
    return new Promise((resolveOuter) => {
        resolveOuter({ data: mockData })
    })
}

// {cacheTime: CACHE_TIME, staleTime: STALE_TIME_LONG}
const CACHE_TIME = 60000
const STALE_TIME_LONG = 60000 // How long it will not re-fetch data from server and show stale results

const useTokenData = (onSuccess, onError) => {
    return useQuery("tokenData", fetchTokenData, {
        onSuccess,
        onError,
        select: (data: any) => {
            return data?.data
        },
        refetchOnWindowFocus: false,
    })
}

export default useTokenData
